apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
- ../resources
- deployment.yaml
- application-initializer.yaml
- argocd-project-app1.yaml
- networkpolicy-deny-ingress.yaml

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: staging
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /metadata/name
      value: quota-staging
    - op: replace
      path: /spec/hard/limits.cpu
      value: 700m
    - op: replace
      path: /spec/hard/limits.memory
      value: 800Mi
    - op: replace
      path: /spec/hard/requests.cpu
      value: 600m
    - op: replace
      path: /spec/hard/requests.memory
      value: 600Mi 
    - op: replace
      path: /spec/hard/pods
      value: 5
    - op: replace
      path: /metadata/namespace
      value: staging
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-staging
    - op: replace
      path: /metadata/namespace
      value: staging


     