apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1

bases:
- ../base

patches:
- target:
    kind: Namespace
    name: default-dev
  patch: |-
    - op: replace
      path: /metadata/name
      value: app1
- target:
    kind: ResourceQuota
    name: resource-quota
  patch: |-
    - op: replace
      path: /metadata/name
      value: quota-app1
    - op: replace
      path: /spec/hard/limits.cpu
      value: 1 
    - op: replace
      path: /spec/hard/services
      value: 10 
- target:
    kind: LimitRange
    name: limit-range
  patch: |-
    - op: replace
      path: /metadata/name
      value: limit-app1