apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: default-dev
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  hard:
    pods: "10"
    requests.cpu: "800m"
    requests.memory: "800Mi"
    limits.cpu: "800m"
    limits.memory: "800Mi"
