apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  source:
    path: staging/app1-dep
    repoURL: https://github.com/cheplorna/argotest-repo.git
    targetRevision: master
  syncPolicy:
  
