apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-staging
  namespace: argocd
spec:
  description: staging project
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: staging
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
